version: '3.1'
networks: 
  banco:
services: 
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./BlogDB:/data/db
    environment:
      MONGO_INITDB_DATABASE: petManange
    ports:
      - 27017:27017
    networks:
      - banco
  backend:
    image: node:10
    volumes: 
      - ./BackEnd:/BackEnd
    ports: 
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - banco
    command: bash ./BackEnd/backend.sh
  frontend:
    image: node:10
    volumes:
      - ./FrontEnd:/FrontEnd
    ports:
      - 8080:8080
    depends_on:
      - backend
    command: bash ./FrontEnd/frontend.sh
