version: '3'
services: 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  backend:
    image: node:10
    volumes: 
      - ./BackEnd:/BackEnd
    ports: 
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    command: bash ./BackEnd/backend.sh
  frontend:
    image: node:10
    volumes:
      - ./FrontEnd:/FrontEnd
    ports:
      - 8080:8080
    depends_on:
      - backend
    command: bash ./FrontEnd/frontend.sh